/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package views;

/**
 *
 * @author ASUS
 */
public class KhuyenMai extends javax.swing.JPanel {

    /** Creates new form KhuyenMai */
    public KhuyenMai() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txbBirthday = new com.toedter.calendar.JDateChooser();
        txbBirthday1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sự kiện", "Số tiền giảm", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 626, 205));

        jLabel1.setText("Tên sự kiện");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 226, -1, -1));

        jLabel2.setText("Số tiền giảm");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 251, -1, -1));

        jLabel3.setText("Ngày bắt đầu");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 279, -1, -1));

        jLabel4.setText("Ngày kết thúc");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 307, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 223, 166, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 251, 166, -1));

        txbBirthday.setDateFormatString("dd/MM/yyyy");
        add(txbBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 279, 166, -1));

        txbBirthday1.setDateFormatString("dd/MM/yyyy");
        add(txbBirthday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 307, 166, -1));

        jButton1.setText("Thêm");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 358, -1, -1));

        jButton2.setText("Sửa");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 358, -1, -1));

        jButton3.setText("Xóa");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 358, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private com.toedter.calendar.JDateChooser txbBirthday;
    private com.toedter.calendar.JDateChooser txbBirthday1;
    // End of variables declaration//GEN-END:variables

}
