/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.KhuyenMaiService;
import services.impl.KhuyenMaiServiceImpl;
import viewModels.KhuyenMaiResponse;

/**
 *
 * @author ASUS
 */
public class KhuyenMai extends javax.swing.JPanel {

    private KhuyenMaiService khuyenMaiService = new KhuyenMaiServiceImpl();
    private DefaultTableModel dtm = new DefaultTableModel();
    private ArrayList<KhuyenMaiResponse> listKhuyenMaiResponses = new ArrayList<>();

    /**
     * Creates new form KhuyenMai
     */
    public KhuyenMai() {
        initComponents();
        listKhuyenMaiResponses = khuyenMaiService.getAll();
        showData(listKhuyenMaiResponses);
        disabled();
    }

    private void clear() {
        txtMaKM.setText("");
        txtTenSK.setText("");
        txtSoTienGiam.setText("");
    }
    private void enabled(){
        txtMaKM.setEnabled(true);
        txtTenSK.setEnabled(true);
        txtSoTienGiam.setEnabled(true);
        btnLuu.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
    }
    private void disabled(){
        txtMaKM.setEnabled(false);
        txtTenSK.setEnabled(false);
        txtSoTienGiam.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }
    private void showData(ArrayList<KhuyenMaiResponse> listKhuyenMaiResponses) {
        dtm = (DefaultTableModel) tblKhuyenMai.getModel();
        dtm.setRowCount(0);
        for (KhuyenMaiResponse o : listKhuyenMaiResponses) {
            dtm.addRow(o.toDataRow());
        }
    }

    private domainModels.KhuyenMai getData() {
        domainModels.KhuyenMai k = new domainModels.KhuyenMai();
        if(txtTenSK.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tên sự kiện không được để trống");
            return null;
        }
        k.setTenSuKien(txtTenSK.getText());
        if(txtSoTienGiam.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tiền sự kiện không được để trống");
            return null;
        }
        try{
            double bien = Double.valueOf(txtSoTienGiam.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Tiền sự kiện không được Nhập chữ");
        }
        if(Double.parseDouble(txtSoTienGiam.getText()) <=0){
            JOptionPane.showMessageDialog(this, "Tiền sự kiện không được nhỏ hơn không");
            return null;
        }
        String tien = txtSoTienGiam.getText();
        Double tienGiam = new Double(tien);
        BigDecimal tg = BigDecimal.valueOf(tienGiam);
        k.setTienGiam(tg);
        return k;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        txtSoTienGiam = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        txtTenSK = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sự kiện", "Tên sự kiện", "Số tiền giảm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 830, 205));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 139, 130));
        jLabel1.setText("Tên sự kiện");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 139, 130));
        jLabel2.setText("Số tiền giảm");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 139, 130));
        jLabel4.setText("Mã khuyến mãi");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        txtMaKM.setEditable(false);
        txtMaKM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtMaKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 210, -1));

        txtSoTienGiam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtSoTienGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 210, -1));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(49, 139, 130));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add_28px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(49, 139, 130));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/edit_28px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(49, 139, 130));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete_28px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(49, 139, 130));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save_28px.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        txtTenSK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtTenSK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked
        int row = tblKhuyenMai.getSelectedRow();
        txtMaKM.setText(tblKhuyenMai.getValueAt(row, 0).toString());
        txtTenSK.setText(tblKhuyenMai.getValueAt(row, 1).toString());
        txtSoTienGiam.setText(tblKhuyenMai.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblKhuyenMaiMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        clear();
        enabled();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        String mess = khuyenMaiService.add(getData());
        JOptionPane.showMessageDialog(this, mess);
        listKhuyenMaiResponses = khuyenMaiService.getAll();
        showData(listKhuyenMaiResponses);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if(txtMaKM.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Mã sự kiện không được để trống");
            return;
        }
        String mess = khuyenMaiService.update(txtMaKM.getText(), getData());
        JOptionPane.showMessageDialog(this, mess);
        listKhuyenMaiResponses = khuyenMaiService.getAll();
        showData(listKhuyenMaiResponses);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(txtMaKM.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Mã sự kiện không được để trống");
            return;
        }
        String mess = khuyenMaiService.delete(txtMaKM.getText());
        JOptionPane.showMessageDialog(this, mess);
        listKhuyenMaiResponses = khuyenMaiService.getAll();
        showData(listKhuyenMaiResponses);
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtSoTienGiam;
    private javax.swing.JTextField txtTenSK;
    // End of variables declaration//GEN-END:variables

}
