/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import application.NewClass;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class LichSuHoaDon extends javax.swing.JPanel {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;

    /**
     * Creates new form LichSuHoaDon
     */
    public LichSuHoaDon() {
        initComponents();
        show();
    }

    public void show() {
        String cautruyvan = "";
        cautruyvan = "SELECT dbo.HoaDon.MaHoaDon, dbo.NhanVien.TenNhanVien, dbo.HoaDon.TenKhachHang, dbo.HoaDon.NgayTao,dbo.HoaDon.NgayThanhToan,dbo.HoaDon.MaKhuyenMai, dbo.HoaDon.TongTien, dbo.HoaDon.TrangThai,dbo.HoaDon.GhiChu\n"
                + "               FROM     dbo.HoaDon INNER JOIN\n"
                + "                                 dbo.NhanVien ON dbo.HoaDon.MaNhanVien = dbo.NhanVien.MaNhanVien\n"
                + "							 where HoaDon.TrangThai =N'Đã thanh toán'";
        ResultSet rs = NewClass.connection.ExcuteQueryGetTable(cautruyvan);
        Object[] obj = new Object[]{"Mã hóa đơn", "Nhân viên", "Khách hàng", "Ngày tạo", "Ngày thanh toán", "Khuyến mãi", "Tổng tiền", "Trạng thái", "Chú thích"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblLSHoaDon.setModel(tableModel);
        try {
            while (rs.next()) {
                Object[] item = new Object[9];
                item[0] = rs.getInt("MaHoaDon");
                item[1] = rs.getString("TenNhanVien");
                item[2] = rs.getString("TenKhachHang");
                item[3] = rs.getString("NgayTao");
                item[4] = rs.getString("NgayThanhToan");
                item[5] = rs.getString("MaKhuyenMai");
                item[6] = rs.getBigDecimal("TongTien");
                item[7] = rs.getString("TrangThai");
                item[8] = rs.getString("GhiChu");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void show1(String ngay,String ngay2) {
        String sql = "SELECT dbo.HoaDon.MaHoaDon, dbo.NhanVien.TenNhanVien, dbo.HoaDon.TenKhachHang, dbo.HoaDon.NgayTao,dbo.HoaDon.NgayThanhToan,dbo.HoaDon.MaKhuyenMai, dbo.HoaDon.TongTien, dbo.HoaDon.TrangThai,dbo.HoaDon.GhiChu\n"
                + "                               FROM     dbo.HoaDon INNER JOIN\n"
                + "                             dbo.NhanVien ON dbo.HoaDon.MaNhanVien = dbo.NhanVien.MaNhanVien \n"
                + "				where HoaDon.TrangThai =N'Đã thanh toán' and Ngay >=? and Ngay <=?";
        Object[] obj = new Object[]{"Mã hóa đơn", "Nhân viên", "Khách hàng", "Ngày tạo", "Ngày thanh toán", "Khuyến mãi", "Tổng tiền", "Trạng thái", "Chú thích"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        tblLSHoaDon.setModel(tableModel);
        try {

            con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-02B3RB0:1433;databaseName=Test1;user=sa;password=123456");
            ps = con.prepareStatement(sql);
            ps.setString(1, ngay);
            ps.setString(2, ngay2);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Object[] item = new Object[9];
                item[0] = rs.getInt("MaHoaDon");
                item[1] = rs.getString("TenNhanVien");
                item[2] = rs.getString("TenKhachHang");
                item[3] = rs.getString("NgayTao");
                item[4] = rs.getString("NgayThanhToan");
                item[5] = rs.getString("MaKhuyenMai");
                item[6] = rs.getBigDecimal("TongTien");
                item[7] = rs.getString("TrangThai");
                item[8] = rs.getString("GhiChu");
                tableModel.addRow(item);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLSHoaDon = new javax.swing.JTable();
        txtNgay = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txtNgay2 = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 139, 130));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconBill.png"))); // NOI18N
        jLabel1.setText("LỊCH SỬ HÓA ĐƠN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 120));

        tblLSHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLSHoaDon);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1190, 520));

        txtNgay.setDateFormatString("yyyy-MM-dd");
        add(txtNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 280, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/search_28px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 90, 30));

        txtNgay2.setDateFormatString("yyyy-MM-dd");
        add(txtNgay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 280, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String date = ((JTextField) txtNgay.getDateEditor().getUiComponent()).getText();
        String date2 = ((JTextField) txtNgay2.getDateEditor().getUiComponent()).getText();
        show1(date, date2);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLSHoaDon;
    private com.toedter.calendar.JDateChooser txtNgay;
    private com.toedter.calendar.JDateChooser txtNgay2;
    // End of variables declaration//GEN-END:variables
}
