/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import bean.DanhMucBean;
import clock.Clock;
import controllers.ManHinhController;
import controllers.ManHinhController2;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author ASUS
 */
public class QLNhanVien extends javax.swing.JFrame{


    /**
     * Creates new form NewJFrame
     */
    public QLNhanVien() {
        initComponents();
        setTitle("QL cửa hàng bán đồ ăn nhanh");
        ManHinhController2 controller = new ManHinhController2(jpnView);
        controller.setView(jpnTrangChu, jlbTrangChu);
        List<DanhMucBean> ListItem = new ArrayList<>();
        ListItem.add(new DanhMucBean("TrangChu", jpnTrangChu, jlbTrangChu));
        controller.setEvent(ListItem);
        setData();

    }

    private void setData() {
        lblDate.setText(String.valueOf(new SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date())));
        Clock cl = new Clock(lblTime);
        cl.start();
        lblTime.setEnabled(true);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnTrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbTrangChu = new javax.swing.JLabel();
        jpnThucDon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlbThucDon = new javax.swing.JLabel();
        jpnDatBan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jlbDatBan = new javax.swing.JLabel();
        jpnHoaDon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jlbHoaDon = new javax.swing.JLabel();
        jpnDoanhThu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jlbDoanhThu = new javax.swing.JLabel();
        jpnNhanVien = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jlbNhanVien = new javax.swing.JLabel();
        jpnDSBan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jlbDSBan = new javax.swing.JLabel();
        jpnThongTin = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jlbThongTin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(51, 51, 51));
        jpnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnTrangChu.setBackground(new java.awt.Color(51, 51, 51));
        jpnTrangChu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/home23px.png"))); // NOI18N
        jpnTrangChu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbTrangChu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jlbTrangChu.setText("Trang chủ");
        jpnTrangChu.add(jlbTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 50));

        jpnThucDon.setBackground(new java.awt.Color(51, 51, 51));
        jpnThucDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Menu_23px.png"))); // NOI18N
        jpnThucDon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbThucDon.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbThucDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbThucDon.setText("Thực đơn");
        jpnThucDon.add(jlbThucDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnThucDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 50));

        jpnDatBan.setBackground(new java.awt.Color(51, 51, 51));
        jpnDatBan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/table_23px.png"))); // NOI18N
        jpnDatBan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbDatBan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbDatBan.setForeground(new java.awt.Color(255, 255, 255));
        jlbDatBan.setText("Đặt bàn");
        jpnDatBan.add(jlbDatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnDatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 50));

        jpnHoaDon.setBackground(new java.awt.Color(51, 51, 51));
        jpnHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bills_23px.png"))); // NOI18N
        jpnHoaDon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbHoaDon.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbHoaDon.setText("Hóa đơn");
        jpnHoaDon.add(jlbHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 50));

        jpnDoanhThu.setBackground(new java.awt.Color(51, 51, 51));
        jpnDoanhThu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Money_23px.png"))); // NOI18N
        jpnDoanhThu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbDoanhThu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        jlbDoanhThu.setText("Doanh thu");
        jpnDoanhThu.add(jlbDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 50));

        jpnNhanVien.setBackground(new java.awt.Color(51, 51, 51));
        jpnNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/management_23px.png"))); // NOI18N
        jpnNhanVien.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbNhanVien.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbNhanVien.setText("Nhân viên");
        jpnNhanVien.add(jlbNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 220, 50));

        jpnDSBan.setBackground(new java.awt.Color(51, 51, 51));
        jpnDSBan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/table_23px.png"))); // NOI18N
        jpnDSBan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbDSBan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbDSBan.setForeground(new java.awt.Color(255, 255, 255));
        jlbDSBan.setText("DS Bàn");
        jpnDSBan.add(jlbDSBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnDSBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 220, 50));

        jpnThongTin.setBackground(new java.awt.Color(51, 51, 51));
        jpnThongTin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/info_23px.png"))); // NOI18N
        jpnThongTin.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbThongTin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbThongTin.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongTin.setText("Khuyến mãi");
        jpnThongTin.add(jlbThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 220, 50));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblName.setText("Name");

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblDate.setText("Date");

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblTime.setText("Time");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Giờ:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Ngày:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Nhân Viên:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTime)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jpnMenu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhanVien().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbDSBan;
    private javax.swing.JLabel jlbDatBan;
    private javax.swing.JLabel jlbDoanhThu;
    private javax.swing.JLabel jlbHoaDon;
    private javax.swing.JLabel jlbNhanVien;
    private javax.swing.JLabel jlbThongTin;
    private javax.swing.JLabel jlbThucDon;
    private javax.swing.JLabel jlbTrangChu;
    private javax.swing.JPanel jpnDSBan;
    private javax.swing.JPanel jpnDatBan;
    private javax.swing.JPanel jpnDoanhThu;
    private javax.swing.JPanel jpnHoaDon;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnNhanVien;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnThongTin;
    private javax.swing.JPanel jpnThucDon;
    private javax.swing.JPanel jpnTrangChu;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
