
package views;

/**
 *
 * @author ASUS
 */
public class ThucDon extends javax.swing.JPanel {

    /**
     * Creates new form ThucDon
     */
    public ThucDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableFood3 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        lbThongtin4 = new javax.swing.JLabel();
        lbMatu3 = new javax.swing.JLabel();
        lbLoai3 = new javax.swing.JLabel();
        lbTen3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbGia6 = new javax.swing.JLabel();
        tfGia3 = new javax.swing.JTextField();
        tfSoLuong3 = new javax.swing.JTextField();
        tfDonVi3 = new javax.swing.JTextField();
        tfTen3 = new javax.swing.JTextField();
        cbLoaiMon3 = new javax.swing.JComboBox<>();
        tfMaMon3 = new javax.swing.JTextField();
        tfTimKiem3 = new javax.swing.JTextField();
        btnTimKiem3 = new javax.swing.JButton();
        lbGia7 = new javax.swing.JLabel();
        tfTenLoai3 = new javax.swing.JTextField();
        lbThongtin1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        tfLink = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lbImages = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        tableFood3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableFood3.setForeground(new java.awt.Color(49, 139, 130));
        tableFood3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã món ăn", "Loại món ăn", "Tên món ăn", "Số lượng", "Đơn vị tính", "Giá bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableFood3.setSelectionForeground(new java.awt.Color(49, 139, 130));
        jScrollPane4.setViewportView(tableFood3);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        lbThongtin4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbThongtin4.setForeground(new java.awt.Color(49, 139, 130));
        lbThongtin4.setText("Thông tin món:");
        lbThongtin4.setToolTipText("");

        lbMatu3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMatu3.setForeground(new java.awt.Color(49, 139, 130));
        lbMatu3.setText("Mã món:");
        lbMatu3.setToolTipText("");

        lbLoai3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLoai3.setForeground(new java.awt.Color(49, 139, 130));
        lbLoai3.setText("Mã loại món:");
        lbLoai3.setToolTipText("");

        lbTen3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTen3.setForeground(new java.awt.Color(49, 139, 130));
        lbTen3.setText("Tên món:");
        lbTen3.setToolTipText("");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(49, 139, 130));
        jLabel26.setText("Đơn vị tính:");
        jLabel26.setToolTipText("");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(49, 139, 130));
        jLabel27.setText("Số lượng:");
        jLabel27.setToolTipText("");

        lbGia6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGia6.setForeground(new java.awt.Color(49, 139, 130));
        lbGia6.setText("Giá tiền:");
        lbGia6.setToolTipText("");

        tfGia3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfGia3.setForeground(new java.awt.Color(49, 139, 130));
        tfGia3.setToolTipText("");

        tfSoLuong3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSoLuong3.setForeground(new java.awt.Color(49, 139, 130));
        tfSoLuong3.setToolTipText("");

        tfDonVi3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDonVi3.setForeground(new java.awt.Color(49, 139, 130));
        tfDonVi3.setToolTipText("");

        tfTen3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfTen3.setForeground(new java.awt.Color(49, 139, 130));
        tfTen3.setToolTipText("");

        cbLoaiMon3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbLoaiMon3.setForeground(new java.awt.Color(49, 139, 130));
        cbLoaiMon3.setToolTipText("");

        tfMaMon3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfMaMon3.setForeground(new java.awt.Color(49, 139, 130));
        tfMaMon3.setToolTipText("");

        tfTimKiem3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfTimKiem3.setForeground(new java.awt.Color(49, 139, 130));
        tfTimKiem3.setToolTipText("");

        btnTimKiem3.setForeground(new java.awt.Color(49, 139, 130));
        btnTimKiem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/search_18px.png"))); // NOI18N
        btnTimKiem3.setText("Tìm");
        btnTimKiem3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTimKiem3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lbGia7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGia7.setForeground(new java.awt.Color(49, 139, 130));
        lbGia7.setText("Tên loại:");
        lbGia7.setToolTipText("");

        tfTenLoai3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfTenLoai3.setForeground(new java.awt.Color(49, 139, 130));
        tfTenLoai3.setToolTipText("");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThongtin4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbGia6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfSoLuong3)
                                    .addComponent(tfGia3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbMatu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfMaMon3)
                                    .addComponent(tfTen3)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(lbLoai3)
                                .addGap(18, 18, 18)
                                .addComponent(cbLoaiMon3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(lbGia7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfTenLoai3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfDonVi3))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfTimKiem3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem3)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTimKiem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbThongtin4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMatu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfMaMon3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTen3)
                    .addComponent(lbTen3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbLoai3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbLoaiMon3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbGia7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTenLoai3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfDonVi3)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSoLuong3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfGia3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(lbGia6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lbThongtin1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbThongtin1.setForeground(new java.awt.Color(49, 139, 130));
        lbThongtin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongtin1.setText("Quản lý món ăn");
        lbThongtin1.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setForeground(new java.awt.Color(49, 139, 130));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add_28px.png"))); // NOI18N
        btnThem.setText("Thêm");

        btnLuu.setForeground(new java.awt.Color(49, 139, 130));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save_28px.png"))); // NOI18N
        btnLuu.setText("Lưu");

        btnSua.setForeground(new java.awt.Color(49, 139, 130));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/edit_28px.png"))); // NOI18N
        btnSua.setText("Sửa");

        btnXoa.setForeground(new java.awt.Color(49, 139, 130));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete_28px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLuu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfLink.setForeground(new java.awt.Color(255, 255, 255));
        tfLink.setBorder(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImages.setForeground(new java.awt.Color(49, 139, 130));
        lbImages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ios_photos_100px.png"))); // NOI18N
        lbImages.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbImages.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbImages.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(lbImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 190, 190));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbThongtin1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lbThongtin1)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý món ăn", jPanel9);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 710));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Quản lý loại món");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTimKiem1;
    private javax.swing.JButton btnTimKiem3;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoaiMon;
    private javax.swing.JComboBox<String> cbLoaiMon1;
    private javax.swing.JComboBox<String> cbLoaiMon3;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbGia1;
    private javax.swing.JLabel lbGia2;
    private javax.swing.JLabel lbGia3;
    private javax.swing.JLabel lbGia6;
    private javax.swing.JLabel lbGia7;
    private javax.swing.JLabel lbImages;
    private javax.swing.JLabel lbLoai;
    private javax.swing.JLabel lbLoai1;
    private javax.swing.JLabel lbLoai3;
    private javax.swing.JLabel lbMatu;
    private javax.swing.JLabel lbMatu1;
    private javax.swing.JLabel lbMatu3;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lbTen1;
    private javax.swing.JLabel lbTen3;
    private javax.swing.JLabel lbThoat;
    private javax.swing.JLabel lbThoat1;
    private javax.swing.JLabel lbThongtin;
    private javax.swing.JLabel lbThongtin1;
    private javax.swing.JLabel lbThongtin2;
    private javax.swing.JLabel lbThongtin4;
    private javax.swing.JTable tableFood;
    private javax.swing.JTable tableFood1;
    private javax.swing.JTable tableFood3;
    private javax.swing.JTextField tfDonVi;
    private javax.swing.JTextField tfDonVi1;
    private javax.swing.JTextField tfDonVi3;
    private javax.swing.JTextField tfGia;
    private javax.swing.JTextField tfGia1;
    private javax.swing.JTextField tfGia3;
    private javax.swing.JTextField tfLink;
    private javax.swing.JTextField tfMaMon;
    private javax.swing.JTextField tfMaMon1;
    private javax.swing.JTextField tfMaMon3;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfSoLuong1;
    private javax.swing.JTextField tfSoLuong3;
    private javax.swing.JTextField tfTen;
    private javax.swing.JTextField tfTen1;
    private javax.swing.JTextField tfTen3;
    private javax.swing.JTextField tfTenLoai;
    private javax.swing.JTextField tfTenLoai1;
    private javax.swing.JTextField tfTenLoai3;
    private javax.swing.JTextField tfTimKiem;
    private javax.swing.JTextField tfTimKiem1;
    private javax.swing.JTextField tfTimKiem3;
    // End of variables declaration//GEN-END:variables
}
